<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Docnet.Core" Version="2.6.0" />
      <PackageReference Include="Microsoft.Data.Sqlite" Version="9.0.4" />
      <PackageReference Include="QRCoder" Version="1.6.0" />
      <PackageReference Include="System.Drawing.Common" Version="9.0.6" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="Ruler\ruler-bottom.png" />
      <EmbeddedResource Include="Ruler\ruler-bottom.png" />
      <None Remove="Ruler\ruler-top.png" />
      <EmbeddedResource Include="Ruler\ruler-top.png" />
    </ItemGroup>

</Project>
