<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net9.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UseWPF>true</UseWPF>
    </PropertyGroup>

    <ItemGroup>
      <EmbeddedResource Update="Resources\en.resx">
        <LastGenOutput>en.Designer.cs</LastGenOutput>
      </EmbeddedResource>
      <EmbeddedResource Update="Resources\Lang.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
        <LastGenOutput>Lang.Designer.cs</LastGenOutput>
      </EmbeddedResource>
    </ItemGroup>

    <ItemGroup>
      <Compile Update="Resources\Lang.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>Lang.resx</DependentUpon>
      </Compile>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Storage\Storage.csproj" />
    </ItemGroup>

</Project>
