//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Interface.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Interface.Resources.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unhandled exception occurred, and the program will close..
        /// </summary>
        public static string Crash_Message {
            get {
                return ResourceManager.GetString("Crash_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured!.
        /// </summary>
        public static string Crash_Title {
            get {
                return ResourceManager.GetString("Crash_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string Import_Browse {
            get {
                return ResourceManager.GetString("Import_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Import_Confirm {
            get {
                return ResourceManager.GetString("Import_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path:.
        /// </summary>
        public static string Import_File {
            get {
                return ResourceManager.GetString("Import_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import an existing Database.
        /// </summary>
        public static string Import_Title {
            get {
                return ResourceManager.GetString("Import_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correction.
        /// </summary>
        public static string MenuTabs_Correct {
            get {
                return ResourceManager.GetString("MenuTabs_Correct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string MenuTabs_Export {
            get {
                return ResourceManager.GetString("MenuTabs_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheets.
        /// </summary>
        public static string MenuTabs_Sheets {
            get {
                return ResourceManager.GetString("MenuTabs_Sheets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks.
        /// </summary>
        public static string MenuTabs_Tasks {
            get {
                return ResourceManager.GetString("MenuTabs_Tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string Password_Change {
            get {
                return ResourceManager.GetString("Password_Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter.
        /// </summary>
        public static string Password_Enter {
            get {
                return ResourceManager.GetString("Password_Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is incorrect..
        /// </summary>
        public static string Password_Failure {
            get {
                return ResourceManager.GetString("Password_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter password:.
        /// </summary>
        public static string Password_Label {
            get {
                return ResourceManager.GetString("Password_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string Password_New {
            get {
                return ResourceManager.GetString("Password_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New database created successfully..
        /// </summary>
        public static string PasswordResult_CreatedSuccess {
            get {
                return ResourceManager.GetString("PasswordResult_CreatedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database could no longer be found, please update the import path..
        /// </summary>
        public static string PasswordResult_DefaultFileMissing {
            get {
                return ResourceManager.GetString("PasswordResult_DefaultFileMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database imported successfully..
        /// </summary>
        public static string PasswordResult_ImportedSuccess {
            get {
                return ResourceManager.GetString("PasswordResult_ImportedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to import database, maybe the path is invalid?.
        /// </summary>
        public static string PasswordResult_ImportFailed {
            get {
                return ResourceManager.GetString("PasswordResult_ImportFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path may not be empty..
        /// </summary>
        public static string PasswordResult_InvalidPath {
            get {
                return ResourceManager.GetString("PasswordResult_InvalidPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Setup_Back {
            get {
                return ResourceManager.GetString("Setup_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string Setup_Browse {
            get {
                return ResourceManager.GetString("Setup_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Setup_Confirm {
            get {
                return ResourceManager.GetString("Setup_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path:.
        /// </summary>
        public static string Setup_File {
            get {
                return ResourceManager.GetString("Setup_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least 8 character long passwords are recommended..
        /// </summary>
        public static string Setup_Hint {
            get {
                return ResourceManager.GetString("Setup_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string Setup_Password {
            get {
                return ResourceManager.GetString("Setup_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new Database.
        /// </summary>
        public static string Setup_Title {
            get {
                return ResourceManager.GetString("Setup_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add question group.
        /// </summary>
        public static string Sheet_AddContainer {
            get {
                return ResourceManager.GetString("Sheet_AddContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add question.
        /// </summary>
        public static string Sheet_AddQuestion {
            get {
                return ResourceManager.GetString("Sheet_AddQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string Sheet_ContainerTitle {
            get {
                return ResourceManager.GetString("Sheet_ContainerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Sheet_Delete {
            get {
                return ResourceManager.GetString("Sheet_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        public static string Sheet_Hide {
            get {
                return ResourceManager.GetString("Sheet_Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List all in order.
        /// </summary>
        public static string Sheet_OptionListOrdered {
            get {
                return ResourceManager.GetString("Sheet_OptionListOrdered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List all shuffled.
        /// </summary>
        public static string Sheet_OptionListShuffled {
            get {
                return ResourceManager.GetString("Sheet_OptionListShuffled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick 1 randomly.
        /// </summary>
        public static string Sheet_OptionPickRandom {
            get {
                return ResourceManager.GetString("Sheet_OptionPickRandom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string Sheet_QuestionTitle {
            get {
                return ResourceManager.GetString("Sheet_QuestionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task sheet.
        /// </summary>
        public static string Sheet_RootTitle {
            get {
                return ResourceManager.GetString("Sheet_RootTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select question.
        /// </summary>
        public static string Sheet_SelectQuestion {
            get {
                return ResourceManager.GetString("Sheet_SelectQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string Sheet_Show {
            get {
                return ResourceManager.GetString("Sheet_Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Task.
        /// </summary>
        public static string Task_Add {
            get {
                return ResourceManager.GetString("Task_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Answer.
        /// </summary>
        public static string Task_AddAnswer {
            get {
                return ResourceManager.GetString("Task_AddAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer.
        /// </summary>
        public static string Task_Answer {
            get {
                return ResourceManager.GetString("Task_Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct.
        /// </summary>
        public static string Task_AnswerCorrect {
            get {
                return ResourceManager.GetString("Task_AnswerCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answers:.
        /// </summary>
        public static string Task_Answers {
            get {
                return ResourceManager.GetString("Task_Answers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Selected Task.
        /// </summary>
        public static string Task_Delete {
            get {
                return ResourceManager.GetString("Task_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Selected Answer.
        /// </summary>
        public static string Task_DeleteAnswer {
            get {
                return ResourceManager.GetString("Task_DeleteAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Task_HasImage {
            get {
                return ResourceManager.GetString("Task_HasImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Image.
        /// </summary>
        public static string Task_Image {
            get {
                return ResourceManager.GetString("Task_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Image.
        /// </summary>
        public static string Task_ImageDelete {
            get {
                return ResourceManager.GetString("Task_ImageDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attached Image.
        /// </summary>
        public static string Task_ImageLabel {
            get {
                return ResourceManager.GetString("Task_ImageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points.
        /// </summary>
        public static string Task_Points {
            get {
                return ResourceManager.GetString("Task_Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string Task_Question {
            get {
                return ResourceManager.GetString("Task_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question:.
        /// </summary>
        public static string Task_QuestionLabel {
            get {
                return ResourceManager.GetString("Task_QuestionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score:.
        /// </summary>
        public static string Task_Score {
            get {
                return ResourceManager.GetString("Task_Score", resourceCulture);
            }
        }
    }
}
